#!/bin/bash  

declare -a arr=( 1 2 3 4 5 6 7 8 12 16 24 32 48 )

 for i in `seq 1 20`;
     do
	for i in "${arr[@]}"
	do
	touch $itest.txt
	java -cp ../dev MST -t $i -s 1 > $itest.txt
	awk '/./{line=$0} END{print line}' $itest.txt >> $i.txt
	rm $itest.txt
	done 
     done 
